services:
  frontend:
    build: ./
    ports:
      - "8080:80"

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./.env

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: